// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - not supported yet.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - not supported yet.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - not supported yet.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - not supported yet.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDRVfyrv5P3HorYBMJ04ybZMXJzw2UEg',
    appId: '1:761944613094:web:d633acf34f5125c094db27',
    messagingSenderId: '761944613094',
    projectId: 'awafi-store',
    authDomain: 'awafi-store.firebaseapp.com',
    storageBucket: 'awafi-store.firebasestorage.app',
    measurementId: 'G-3CKV56GS68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcrUh25l1UadJSHqM6ganw08HIzP6nu8',
    appId: '1:761944613094:android:15525f7a9173a3a294db27',
    messagingSenderId: '761944613094',
    projectId: 'awafi-store',
    storageBucket: 'awafi-store.firebasestorage.app',
  );
}